version: '3.1'

services:


  home.redis:
    image: redis
    ports:
      - "6379:6379"


  home.nginx:
    image: nginx:latest
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - home.api.csharp
      - home.api.express
      - home.api.http



  home.api.csharp:
    build:
      context: ./backend/csharp-api
    env_file:
      - ./jwt.env
#    ports:
#      - "5000:5000"


  home.api.express:
    build:
      context: ./backend/express-api
    env_file:
      - ./jwt.env
    environment:
      - SERVER_NAME=ExpressServer
#      - SERVER_PORT=4000
#    ports:
#      - "5555:3000"

  home.api.http:
    build:
      context: ./backend/http-api
    env_file:
      - ./jwt.env
    environment:
      - SERVER_NAME=HttpServer
#    ports:
#      - "7777:3000"

  home.api.hiload1:
    build:
      context: ./backend/http-api
    env_file:
      - ./jwt.env
    environment:
      - SERVER_NAME=HiLoad First

  home.api.hiload2:
    build:
      context: ./backend/http-api
    env_file:
      - ./jwt.env
    environment:
      - SERVER_NAME=HiLoad Second